#!/usr/bin/env python3
"""
Direct Anthropic API call with Prompt Caching.

Replaces `claude --print agents/xxx.md` for cost efficiency:
  - System prompt is cached (ephemeral cache, ~5 min TTL)
    → 90% discount on repeated/retry calls within cache window
  - Claude outputs analysis JSON ONLY (not HTML)
    → saves ~4,000 output tokens/run (HTML is generated by generate_html.py)

Usage:
    python3 scripts/call_claude.py --type kospi [--date 2026-04-14]
    python3 scripts/call_claude.py --type us
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import anthropic
import pytz

BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "data"
KST = pytz.timezone("Asia/Seoul")

# ─────────────────────────────────────────────────────────────────────────────
# System prompts (CACHED — these are billed at 10% on cache hits)
# ─────────────────────────────────────────────────────────────────────────────

KOSPI_SYSTEM_PROMPT = """\
너는 20년 경력의 한국·미국 주식시장 투자 전략가다.
제공된 시장 데이터와 뉴스 요약을 분석하여 오늘 코스피 시초가 방향을 예측한다.

## 분석 방법론

### 방향 예측 우선순위
1. 미국 증시 종가 (나스닥·S&P500·다우) — 가장 강한 선행 지표
   - 나스닥 +1% 이상이면 코스피 IT·반도체 섹터 갭 상승 가능성 높음
   - 다우 단독 강세(나스닥 약세)는 코스피에 제한적 영향
2. NQ선물·YM선물 현재 방향 — 실시간 미국 시장 심리 반영
3. 필라델피아 반도체(SOX) — 삼성전자·SK하이닉스 시초가 직결
   - SOX +2% 이상이면 반도체 비중이 큰 코스피에 직접 수혜
4. EWY (한국 ETF) — 외국인 수급 방향의 선행 지표
   - EWY 상승 + 원화 강세 = 외국인 순매수 환경
5. VIX + 공포탐욕지수 — 글로벌 리스크 선호도
   - VIX 20 이하 = 리스크온, 20~30 = 주의, 30 이상 = 리스크오프
   - 공포탐욕 25 이하 = 극단적 공포(역발상 매수 기회 가능)
6. 달러(DXY/USD-KRW) — 외국인 자금 흐름
   - 달러 약세(DXY 하락) + 원화 강세 = 외국인 유입 유리
7. WTI 유가 — 인플레이션 우려·에너지 섹터 영향
   - 유가 급등 = 인플레 우려로 성장주 부담

### 종목 선택 규칙 (잭 켈로그 MA20 전략)
잭 켈로그(Zack Kellogg)의 20일 이동평균선 전략은 단기 모멘텀 스윙 기법이다.

선별 기준:
- kospi_candidates 배열에서 ma20_signal이 "crossing_up"인 종목 최우선
- ma20_signal이 "above"이고 ma20_dist_pct가 작은 종목 차선
- price, change_pct, ma20, ma20_dist_pct, ma200, ma200_dist_pct는 JSON 데이터값 그대로 사용 (변경 금지)
- 3~5개 선택. 모멘텀과 MA200 구조적 강세 종목 우선 배치
- golden: true 조건 → MA200도 함께 돌파하거나 크게 상회한 종목

실행 가이드 작성 규칙:
- 구체적 진입 구간 (시가 기준 ±X원 또는 ±X%)
- 명확한 목표가와 손절가
- 시장 전체 방향과 종목의 연관성 설명

### 예측 근거(reasons) 작성 규칙
- 최대 4개, 중요도 내림차순 (배열 앞쪽 = 코스피 영향 큰 지표)
- 각 항목은 완전한 한국어 문장. 이모지 1개로 시작
- 지표·수치는 반드시 <b>수치</b> 형식으로 강조
- 단순 나열 금지. 지표가 코스피에 미치는 영향까지 설명할 것
- 문체는 반드시 '~했어요', '~있어요', '~됩니다' 대신 '~됐어요' 등 ~요 체로 작성한다
- 쉼표와 마침표로 호흡을 나누고, em dash(—)로만 이어붙이지 않는다

이모지 가이드:
- 🚀 미국 지수·기술주 강세 시그널
- 💡 반도체·SOX 지수 관련 시그널
- 🇺🇸 수급·ETF·환율 관련 시그널
- 😰 VIX·공포지수·리스크 관련 시그널
- 📉 하락 또는 약세 시그널
- 🏦 금리·연준·매크로 관련 시그널

### 예측 근거 섹션 타이틀(reason_title) 작성 규칙
예측 근거 섹션 상단에 표시되는 훅 타이틀. 30자 이내.

- **상승 우위**: 왜 오를지를 드라이빙하는 핵심 팩터 1~2개를 훅으로. 구체적 수치 하나 포함 권장.
  예시: "왜 오를까? — 나스닥·반도체 동시 강세", "외인 2.7조 순매수, 오늘도 상승 이어간다"
- **하락 우위**: 경보성 톤 또는 핵심 위험 요인 명시.
  예시: "긴급 점검: 기술주 약세 속 하락 시그널", "왜 내릴까? — VIX 급등·달러 강세"
- **중립**: 질문형으로 방향성 혼재 표현.
  예시: "오를까 내릴까? 오늘의 핵심 변수", "방향 혼재 — 판단 기준 N가지"

## 출력 형식

순수 JSON만 출력한다. 마크다운 코드블록(```), 설명 텍스트, 앞뒤 줄바꿈 없이 오직 JSON.

{
  "prediction": {
    "direction": "상승 우위",
    "up_pct": 65,
    "down_pct": 35,
    "confidence": 78
  },
  "reason_title": "왜 오를까? — 나스닥·반도체 동시 강세",
  "reasons": [
    "🚀 나스닥은 <b>+X.X%</b>로 마감하며 기술주가 전반적으로 강세를 보였어요. MSFT는 <b>+X.X%</b>로 MA20을 돌파했고, 코스피 IT·플랫폼 섹터의 갭 상승을 기대할 근거가 돼요.",
    "💡 필라델피아 반도체 지수 SOX는 <b>+X.X%</b>로 연속 강세예요. SK하이닉스·삼성전자 시초가에 상승 압력이 작용할 여지가 있어요.",
    "🇺🇸 한국 ETF EWY는 <b>+X.X%</b>로 상승했고, 달러/원은 <b>X,XXX원</b>으로 원화 강세예요. 외국인 순매수 환경이 조성되고 있어요.",
    "😰 공포탐욕지수는 <b>XX</b>로 극단적 공포 구간에 있어요. 단기 역발상 매수 기회가 될 수 있으나, 추세 확인이 선행돼야 해요."
  ],
  "stock_picks": [
    {
      "name": "종목명",
      "price": "000,000원",
      "change": "+X.XX%",
      "change_cls": "up",
      "signal": "MA20 상향 돌파",
      "golden": false,
      "ma20_dist_pct": 2.1,
      "ma200_dist_pct": 15.3,
      "scenario_tag": "모멘텀 가속",
      "scenario": "시나리오 설명 문장. 왜 이 종목인지, 어떤 촉매가 있는지 구체적으로 서술한다.",
      "action_guide": "시가 X원 이내 진입. 목표: Y원(+X.X%) / 손절: Z원 이탈 시."
    }
  ]
}
"""

US_SYSTEM_PROMPT = """\
너는 20년 경력의 미국 주식시장 투자 전략가다.
제공된 시장 데이터와 뉴스 요약을 분석하여 오늘 미국 증시(S&P500) 개장 방향을 예측한다.

## 분석 방법론

### 방향 예측 우선순위
1. 아시아·유럽 증시 흐름 — 미국 개장 전 글로벌 심리 확인
   - 일본(닛케이)·한국(코스피)·중국(상해) 동반 강세 = 리스크온 신호
   - 유럽(DAX·FTSE) 방향도 함께 확인
2. S&P500·NQ·YM 선물 프리마켓 방향 — 가장 직접적인 선행 지표
   - 선물 +0.5% 이상이면 강세 개장 가능성 높음
3. VIX + 공포탐욕지수 — 시장 심리 온도계
   - VIX 20 이하 = 리스크온 / 30 이상 = 리스크오프
   - 공포탐욕 25 이하 = 극단적 공포 (역발상 기회 가능)
4. 미국 10년 국채금리 + DXY — 거시 환경
   - 금리 급등 + 달러 강세 = 성장주·기술주 부담
   - 금리 안정 + 달러 약세 = 주식 우호 환경
5. 주요 경제지표 발표 일정
   - CPI·PPI·PCE — 인플레이션 지표, 연준 기대 변화
   - 실업률·비농업고용 — 경기 강도 판단
   - GDP·소매판매 — 소비·성장 모멘텀
   - 연준 의원 발언·FOMC 회의 — 금리 기대 직접 영향
6. 빅테크 프리마켓 수급 — 시가총액 상위 종목이 지수를 끌어당김
   - NVDA·AAPL·MSFT·META·GOOGL·AMZN·TSLA 동향 확인

### 종목 선택 규칙 (잭 켈로그 MA20 전략)
잭 켈로그(Zack Kellogg)의 20일 이동평균선 전략은 단기 모멘텀 스윙 기법이다.

선별 기준:
- us_candidates 배열에서 ma20_signal이 "crossing_up"인 종목 최우선
- ma20_signal이 "above"이고 ma20_dist_pct가 작은 종목 차선
- price, change_pct, ma20, ma20_dist_pct, ma200, ma200_dist_pct는 JSON 데이터값 그대로 사용 (변경 금지)
- 3~5개 선택. 반도체·빅테크·금융·에너지 섹터 분산 고려
- golden: true 조건 → MA200도 함께 돌파하거나 크게 상회

실행 가이드 작성 규칙:
- 티커와 회사명 모두 표기 (예: "NVDA (엔비디아)")
- 구체적 진입 구간 (시가 기준 ±$X 또는 ±X%)
- 명확한 목표가와 손절가
- 해당 종목이 오늘 시장 방향과 어떻게 연관되는지 설명

### 예측 근거(reasons) 작성 규칙
- 최대 5개, 중요도 내림차순
- 각 항목은 완전한 한국어 문장. 이모지 1개로 시작
- 지표·수치는 반드시 <b>수치</b> 형식으로 강조
- 단순 수치 나열 금지. 수치가 시장에 미치는 영향까지 설명
- 문체는 반드시 '~했어요', '~있어요', '~됐어요' 등 ~요 체로 작성한다
- 쉼표와 마침표로 호흡을 나누고, em dash(—)로만 이어붙이지 않는다

이모지 가이드:
- 🌏 아시아·유럽 증시
- 📈 선물·지수 강세
- 📉 선물·지수 약세
- 😰 VIX·공포지수
- 🏦 금리·연준·매크로
- 💹 빅테크·섹터 수급
- 🛢️ 유가·원자재

### 예측 근거 섹션 타이틀(reason_title) 작성 규칙
예측 근거 섹션 상단에 표시되는 훅 타이틀. 30자 이내.

- **상승 우위**: 왜 오를지를 드라이빙하는 핵심 팩터 1~2개를 훅으로. 구체적 수치 하나 포함 권장.
  예시: "왜 오를까? — 선물 강세·빅테크 반등", "S&P500 저점 반등, 오늘도 상승 이어간다"
- **하락 우위**: 경보성 톤 또는 핵심 위험 요인 명시.
  예시: "긴급 점검: 선물 약세·VIX 급등", "왜 내릴까? — 빅테크 매도세·금리 상승"
- **중립**: 질문형으로 방향성 혼재 표현.
  예시: "오를까 내릴까? 오늘의 핵심 변수", "방향 혼재 — 판단 기준 N가지"

## 출력 형식

순수 JSON만 출력한다. 마크다운 코드블록(```), 설명 텍스트, 앞뒤 줄바꿈 없이 오직 JSON.

{
  "prediction": {
    "direction": "상승 우위",
    "up_pct": 60,
    "down_pct": 40,
    "confidence": 72
  },
  "reason_title": "왜 오를까? — 선물 강세·빅테크 반등",
  "reasons": [
    "🌏 아시아 증시는 일본 <b>+X.X%</b>, 한국 <b>+X.X%</b>로 동반 강세를 보이며 리스크온 분위기가 형성됐어요.",
    "📈 S&P500 선물은 <b>+X.X%</b>, NQ 선물은 <b>+X.X%</b>로 프리마켓이 강하게 출발하고 있어요.",
    "😰 VIX는 <b>XX.X</b>로 전일 대비 하락하며 변동성 완화 신호를 보이고 있어요.",
    "🏦 미국채 10년물은 <b>X.XX%</b>로 안정세를 유지하며 성장주에 우호적인 매크로 환경이 이어지고 있어요.",
    "💹 NVDA는 프리마켓에서 <b>+X.X%</b>로 강세를 보이고, 반도체 섹터 전반의 매수세가 집중될 가능성이 있어요."
  ],
  "stock_picks": [
    {
      "name": "NVDA (엔비디아)",
      "price": "$XXX.XX",
      "change": "+X.XX%",
      "change_cls": "up",
      "signal": "MA20 상향 돌파",
      "golden": false,
      "ma20_dist_pct": 3.2,
      "ma200_dist_pct": 22.1,
      "scenario_tag": "모멘텀 가속",
      "scenario": "시나리오 설명 문장. 왜 이 종목인지, 어떤 촉매가 있는지 구체적으로 서술한다.",
      "action_guide": "시가 $XXX 이내 진입. 목표: $YYY(+X.X%) / 손절: $ZZZ 이탈 시."
    }
  ]
}
"""


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def load_config() -> dict:
    config_file = BASE_DIR / "config.json"
    if config_file.exists():
        with open(config_file, encoding="utf-8") as f:
            return json.load(f)
    return {}


def get_anthropic_api_key() -> str:
    key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not key:
        cfg = load_config()
        key = cfg.get("anthropic", {}).get("api_key", "")
    if not key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY not set. "
            "Set the environment variable or add anthropic.api_key to config.json"
        )
    return key


def load_market_data(briefing_type: str) -> dict:
    path = DATA_DIR / f"latest_{briefing_type}.json"
    if not path.exists():
        raise FileNotFoundError(f"Market data not found: {path}")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_news_summary(briefing_type: str) -> dict:
    path = DATA_DIR / f"news_summary_{briefing_type}.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_analysis(briefing_type: str, analysis: dict) -> None:
    path = DATA_DIR / f"analysis_{briefing_type}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(analysis, f, ensure_ascii=False, indent=2)
    print(f"[call_claude] Saved → {path}")


def save_prediction_to_briefings(briefing_type: str, date_str: str, analysis: dict) -> None:
    """Append or update the prediction record in data/briefings.json for accuracy tracking."""
    path = DATA_DIR / "briefings.json"
    if path.exists():
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    else:
        data = {"briefings": []}

    pred = analysis.get("prediction", {})
    briefings = data.setdefault("briefings", [])

    existing_idx = next(
        (i for i, b in enumerate(briefings) if b["date"] == date_str and b["type"] == briefing_type),
        None,
    )

    entry = {
        "date": date_str,
        "type": briefing_type,
        "predicted_direction": pred.get("direction", ""),
        "up_pct": pred.get("up_pct", 0),
        "down_pct": pred.get("down_pct", 0),
        "confidence": pred.get("confidence", 0),
        "actual_direction": None,
        "actual_change_pct": None,
        "is_correct": None,
        "generated_at": datetime.now(KST).isoformat(),
        "checked_at": None,
    }

    if existing_idx is not None:
        # Preserve existing actual result (don't overwrite accuracy data on re-run)
        prev = briefings[existing_idx]
        entry["actual_direction"] = prev.get("actual_direction")
        entry["actual_change_pct"] = prev.get("actual_change_pct")
        entry["is_correct"] = prev.get("is_correct")
        entry["checked_at"] = prev.get("checked_at")
        briefings[existing_idx] = entry
    else:
        briefings.append(entry)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"[call_claude] Saved prediction to briefings.json ({date_str}, {briefing_type})")


def save_telegram_message(briefing_type: str, date_str: str, analysis: dict) -> None:
    """analysis JSON → telegram_message_{type}.txt 생성 (매 실행마다 최신화)."""
    import re

    def strip_html(text: str) -> str:
        return re.sub(r"<[^>]+>", "", str(text))

    web_base = os.environ.get("WEB_BASE_URL", "")
    if not web_base:
        cfg = load_config()
        web_base = cfg.get("web", {}).get("base_url", "https://pulum0083.github.io/daily30")
    web_base = web_base.rstrip("/")

    date_display = datetime.strptime(date_str, "%Y-%m-%d").strftime("%Y.%m.%d")

    pred = analysis.get("prediction", {})
    direction = pred.get("direction", "알 수 없음")
    up_pct = pred.get("up_pct", "?")
    confidence = pred.get("confidence", "?")
    reason_title = strip_html(analysis.get("reason_title", ""))
    reasons = analysis.get("reasons", [])

    if briefing_type == "kospi":
        header = f"🇰🇷 코스피 시초가 브리핑 | {date_display}"
        link = f"{web_base}/briefings/ko/{date_str}/"
    else:
        header = f"🇺🇸 미국 시장 브리핑 | {date_display}"
        link = f"{web_base}/briefings/us/{date_str}/"

    lines = [
        header,
        "",
        f"📊 예측: {direction} ({up_pct}%)",
        f"신뢰도: {confidence}%",
    ]

    if reason_title:
        lines += ["", f"💬 {reason_title}"]

    if reasons:
        lines += ["", "핵심 시그널:"]
        for r in reasons[:4]:
            lines.append(f"• {strip_html(r)}")

    lines += ["", f"🔗 상세 분석 → {link}"]

    msg = "\n".join(lines)
    path = DATA_DIR / f"telegram_message_{briefing_type}.txt"
    with open(path, "w", encoding="utf-8") as f:
        f.write(msg)
    print(f"[call_claude] Telegram message saved → {path}")


def extract_json(text: str) -> dict:
    """Parse JSON from Claude's response, stripping any accidental markdown fences."""
    text = text.strip()
    # Strip markdown code fences if present
    if text.startswith("```"):
        lines = text.split("\n")
        # Remove first line (```json or ```) and last line (```)
        text = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
    return json.loads(text)


# ─────────────────────────────────────────────────────────────────────────────
# Core: Call Claude API with Prompt Caching
# ─────────────────────────────────────────────────────────────────────────────

def call_claude(briefing_type: str, date_str: str) -> dict:
    client = anthropic.Anthropic(
        api_key=get_anthropic_api_key(),
        default_headers={"anthropic-beta": "prompt-caching-2024-07-31"},
    )

    system_prompt = KOSPI_SYSTEM_PROMPT if briefing_type == "kospi" else US_SYSTEM_PROMPT

    market_data = load_market_data(briefing_type)
    news_summary = load_news_summary(briefing_type)

    # Build user message: dynamic data (not cached)
    candidates_key = "kospi_candidates" if briefing_type == "kospi" else "us_candidates"
    # Pass only what's needed for analysis — exclude heavy market_data_js (sidebar only)
    analysis_data = {
        k: v for k, v in market_data.items()
        if k not in ("market_data_js",)  # sidebar data not needed for analysis
    }

    user_content = f"오늘 날짜: {date_str}\n\n"
    user_content += f"시장 데이터:\n{json.dumps(analysis_data, ensure_ascii=False, indent=2)}\n\n"
    if news_summary:
        user_content += f"뉴스 요약:\n{json.dumps(news_summary, ensure_ascii=False, indent=2)}\n"

    print(f"[call_claude] Calling Claude API (type={briefing_type}, date={date_str})")
    print(f"[call_claude] User message: ~{len(user_content)//4} tokens estimated")

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        system=[
            {
                "type": "text",
                "text": system_prompt,
                "cache_control": {"type": "ephemeral"},  # Cache the system prompt
            }
        ],
        messages=[
            {"role": "user", "content": user_content}
        ],
    )

    # Log cache usage if available
    usage = response.usage
    if hasattr(usage, "cache_creation_input_tokens"):
        print(f"[call_claude] Cache created: {usage.cache_creation_input_tokens} tokens")
    if hasattr(usage, "cache_read_input_tokens"):
        print(f"[call_claude] Cache hit: {usage.cache_read_input_tokens} tokens (90% discount)")
    print(f"[call_claude] Input: {usage.input_tokens}, Output: {usage.output_tokens} tokens")

    raw_text = response.content[0].text
    return extract_json(raw_text)


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Call Claude API with Prompt Caching")
    parser.add_argument("--type", choices=["kospi", "us"], required=True)
    parser.add_argument("--date", default=None, help="Date string (YYYY-MM-DD)")
    parser.add_argument(
        "--no-html", action="store_true",
        help="Skip HTML generation (useful for testing)"
    )
    args = parser.parse_args()

    date_str = args.date or datetime.now(KST).strftime("%Y-%m-%d")

    # 1. Call Claude → get analysis JSON
    try:
        analysis = call_claude(args.type, date_str)
    except Exception as e:
        print(f"[call_claude] ERROR calling Claude API: {e}", file=sys.stderr)
        sys.exit(1)

    # 2. Save analysis JSON
    save_analysis(args.type, analysis)

    # 2b. Record prediction in briefings.json for accuracy tracking
    save_prediction_to_briefings(args.type, date_str, analysis)

    # 2c. Generate telegram message (always fresh — overwrites stale txt)
    save_telegram_message(args.type, date_str, analysis)

    # 3. Generate HTML (unless --no-html)
    if not args.no_html:
        data_file = DATA_DIR / f"latest_{args.type}.json"
        html_script = BASE_DIR / "scripts" / "generate_html.py"
        cmd = [
            sys.executable, str(html_script),
            "--type", args.type,
            "--data-file", str(data_file),
            "--date", date_str,
        ]
        print(f"[call_claude] Generating HTML: {' '.join(cmd)}")
        result = subprocess.run(cmd)
        if result.returncode != 0:
            print("[call_claude] WARNING: HTML generation failed", file=sys.stderr)

    print(f"[call_claude] Done. direction={analysis.get('prediction', {}).get('direction')}")


if __name__ == "__main__":
    main()
